sonar.organization=signalsafesoftware
sonar.projectKey=SignalSafeSoftware_tree-spec
sonar.projectName=tree-spec-python
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/test_*.py,tests/**/*_test.py

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.venv/**,**/.mypy_cache/**,**/__pycache__/**,tests/**
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.venv/**

sonar.python.coverage.reportPaths=coverage.xml
